### ISSUE TITLE
[Suggestion] Add option to only click Wrath Cookies during Cookie Storm

### ISSUE THREAD

**Issue by lmmfranco** [orchidalloy/FortuneHelper#3]
Sometime we don't want to auto click wraft cookies at all, but they end up spawning during Cookie Storm

**Comment by hollowstrawberry** [comment]
Right! I'll make it so that it doesn't count storm cookies as wrath cookies

**Comment by hollowstrawberry** [comment]
Fixed, let me know if it works

**Comment by lmmfranco** [comment]
It worked perfectly
